### ISSUE TITLE
Can i ask how to train this parser?

### ISSUE THREAD

**Issue by Yeom** [BLLIP/bllip-parser#27]
First, i'm sorry that my english level(?) is so low
I'm a student in South Korea
And i wonder about how can i train the new data?
Can i train the new corpus? i can't find how to train the data.
Should i do in first-stage TRAIN directory?
i'm so curious.

**Comment by dmcc** [comment]
Thanks for the question. Yes, training should be run from the `first-stage/TRAIN` directory with the `trainParser` script. There's some information about what the script expects as arguments here:

   https://github.com/BLLIP/bllip-parser/blob/master/first-stage/TRAIN/README.rst

For training data, it depends on what type of text you'd like to parse. Ideally, the training data would be similar in style to the text you'd like to parse. There are various treebanks available -- some are available for [free](http://stackoverflow.com/questions/8949517/is-there-any-treebank-for-free/18665260#18665260), others can be licensed from the [LDC](https://www.ldc.upenn.edu/).

**Comment by Yeom** [comment]
Can i ask more?
1) I want to save existing data and add my new training data ,is that possible?
For example I want to get train data that original data and my new data.
Can you understand this? Hmm....If i train the data then the original data is blow up? or remain?

2)  I saw the DATA directory in first-stage and data files are numbers....
     Should i run the some program to get the data like that? Can you tell me how can i get training data form?
Thank you for reading!
