### ISSUE TITLE
Update PyPI version

### ISSUE THREAD

**Issue by ashishbaghudana** [BLLIP/bllip-parser#45]
Hello, thanks for the great parser and the interface to Python! 

While the Github version reflects updates to support Python 3, the version hosted on PyPi still does not. Could this be updated?

**Comment by dmcc** [comment]
Hi @ashishbaghudana, thanks for the comment. I've been waiting a little on it to make sure that it's stable (also on vacation) but hope to get to this soon.

**Comment by dmcc** [comment]
Python 3 version released!
