### ISSUE TITLE
bllip parser in Server

### ISSUE THREAD

**Issue by jofatmofn** [BLLIP/bllip-parser#57]
Please let me know if bllip parser can be used in this fashion. I am using Flask.

During start-up:
`rrp = RerankingParser.fetch_and_load('WSJ-PTB3', verbose=True)`

While processing (multiple concurrent) requests from clients (Same object rrp is reused):
`		constituency_lisp_string = str(rrp.parse_tagged(tokens, possible_tags=dict(enumerate(postags)))[0].ptb_parse)`

**Comment by dmcc** [comment]
It's fine to reuse a RerankingParser object, but BLLIP's multithreading
doesn't work properly (see #16) so you'll need to ensure that only one
parse is happening at a time (try something like
https://stackoverflow.com/questions/5185568/python-conditional-with-lock-design
).

**Comment by jofatmofn** [comment]
Thanks. If I need to have multiple concurrent parses, then is it okay to maintain a pool of rrp objects?

**Comment by dmcc** [comment]
If each RRP is in a separate process, it will be alright (not sure if flask
supports this). The RRPs are in the same process, they will almost
certainly corrupt each other if they're used simultaneously, unfortunately.
