### ISSUE TITLE
Compilation error when installing from pip

### ISSUE THREAD

**Issue by mbasaglia** [BLLIP/bllip-parser#69]
`pip install bllipparser` fails. The output shows a bunch of stuff but I think this is the relevant error:

```
first-stage/PARSE/swig/wrapper.C: In function ‘void SwigPyStaticVar_dealloc(PyDescrObject*)’:
first-stage/PARSE/swig/wrapper.C:3309:3: error: ‘_PyObject_GC_UNTRACK’ was not declared in this scope; did you mean ‘PyObject_GC_UnTrack’?
```

OS: Ubuntu 21.04
Python: Python 3.9.5

**Comment by dmcc** [comment]
This might be the same issue as https://github.com/BLLIP/bllip-parser/issues/68 -- can you see if the same workaround works for you?

(meanwhile, I'll work on a new release...)

**Comment by dmcc** [comment]
I'm hoping the new release will fix it -- please reopen if there's still an issue.
